"""empty message

Revision ID: 35f2c8f38b87
Revises: 42cd873a6bd4
Create Date: 2014-08-24 20:17:57.832310

"""

# revision identifiers, used by Alembic.
revision = '35f2c8f38b87'
down_revision = '42cd873a6bd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stop_times', sa.Column('arrival_time_hour', sa.Integer(), nullable=True))
    op.add_column('stop_times', sa.Column('arrival_time_minute', sa.Integer(), nullable=True))
    op.add_column('stop_times', sa.Column('arrival_time_second', sa.Integer(), nullable=True))
    op.add_column('stop_times', sa.Column('departure_time_hour', sa.Integer(), nullable=True))
    op.add_column('stop_times', sa.Column('departure_time_minute', sa.Integer(), nullable=True))
    op.add_column('stop_times', sa.Column('departure_time_second', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stop_times_arrival_time_hour'), 'stop_times', ['arrival_time_hour'], unique=False)
    op.create_index(op.f('ix_stop_times_arrival_time_minute'), 'stop_times', ['arrival_time_minute'], unique=False)
    op.create_index(op.f('ix_stop_times_arrival_time_second'), 'stop_times', ['arrival_time_second'], unique=False)
    op.create_index(op.f('ix_stop_times_departure_time_hour'), 'stop_times', ['departure_time_hour'], unique=False)
    op.create_index(op.f('ix_stop_times_departure_time_minute'), 'stop_times', ['departure_time_minute'], unique=False)
    op.create_index(op.f('ix_stop_times_departure_time_second'), 'stop_times', ['departure_time_second'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_times_departure_time_second'), table_name='stop_times')
    op.drop_index(op.f('ix_stop_times_departure_time_minute'), table_name='stop_times')
    op.drop_index(op.f('ix_stop_times_departure_time_hour'), table_name='stop_times')
    op.drop_index(op.f('ix_stop_times_arrival_time_second'), table_name='stop_times')
    op.drop_index(op.f('ix_stop_times_arrival_time_minute'), table_name='stop_times')
    op.drop_index(op.f('ix_stop_times_arrival_time_hour'), table_name='stop_times')
    op.drop_column('stop_times', 'departure_time_second')
    op.drop_column('stop_times', 'departure_time_minute')
    op.drop_column('stop_times', 'departure_time_hour')
    op.drop_column('stop_times', 'arrival_time_second')
    op.drop_column('stop_times', 'arrival_time_minute')
    op.drop_column('stop_times', 'arrival_time_hour')
    ### end Alembic commands ###
